version: "3"

services:
  nginx:
    container_name: nginx
    ports:
      - "443:443"
    build: ./requirements/nginx
    env_file: .env
    networks:
      - network
    restart: always
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    env_file: .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/data/wordpress
      o: bind


networks:
  network:
    driver: bridge